### ISSUE TITLE
db-updater suggestion

### ISSUE THREAD

**Issue by alangham** [flightaware/firestarter#27]
I wanted to see the positions table's contents but the postgresql-client wasn't installed. (That's the only one I checked for.) I didn't want to install it while in the container, so I added it to the db-updater Docker file which worked nicely. On line 5 I changed:

RUN apt-get update && apt-get install -y libpq-dev gcc make sqlite3

to

RUN apt-get update && apt-get install -y libpq-dev gcc make sqlite3 postgresql-client

Great app and service, btw! Lots of fun digging into it :)

**Comment by NasaGeek** [comment]
Thanks, Arthur. I've applied your suggestion.
